"""Вход"""
locator_button_login_customer = ".btn.btn-primary.btn-lg"
locator_button_your_name = "#userSelect"
locator_button_harry_potter = "#option.ng-binding.nth-child(3)"
locator_button_login = "button.btn:nth-child(2)"
locator_button_back_home = ".home"
locator_button_logout = ".logout"
locator_button_account_select = "#accountSelect"
locator_button_deposit = "button.btn:nth-child(2)"
locator_field_amount = ".form-control"
locator_field_amount_withdrawn = "//html/body/div/div/div[2]/div/div[4]/div/form/div/input"
locator_deposit = ".btn-default"
locator_button_withdrawl = "button.btn-lg:nth-child(3)"
locator_button_withdraw = ".btn-default"
locator_message_successful = ".error"
locator_button_with_drawl = "//button[@ng-class= 'btnClass3']"
locator_button_transactions = "button.btn-lg:nth-child(1)"
locator_scroll_right = "button.btn-primary:nth-child(3)"
locator_transactions_reset = ".fixedTopBox > button:nth-child(3)"
locator_button_login_bank_manager = "div.center:nth-child(3) > button:nth-child(1)"
locator_button_add_customer = "button.btn-lg:nth-child(1)"
locator_first_name = "//html/body/div/div/div[2]/div/div[2]/div/div/form/div[1]/input"
locator_last_name ="div.form-group:nth-child(2) > input:nth-child(2)"
locator_post_code = "div.form-group:nth-child(3) > input:nth-child(2)"
locator_button_add_customer_confirm = "button.btn:nth-child(4)"
locator_assert_td_ng_binding_1 = "td.ng-binding"
locator_button_list_customer = "button.btn-lg:nth-child(3)"
locator_search_customer = ".form-control"
locator_button_open_account = "button.btn:nth-child(2)"
locator_customer_name = '//*[@id="userSelect"]'
locator_customer_potter = "option.ng-binding:nth-child(3)"
locator_currency = "#currency"
locator_currency_rupee = "//html/body/div/div/div[2]/div/div[2]/div/div/form/div[2]/select/option[4]"
locator_process = "form.ng-dirty > button:nth-child(3)"